# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

echo "Welcome to $HOSTNAME, $USER."
echo ""
echo "Uptime:"
echo "$(/usr/bin/uptime)"
echo ""
echo "Who's online:"
echo "$(/usr/bin/w -h)"
echo ""
if [ -x /usr/bin/fortune ]; then
   /usr/bin/fortune
else
   echo "Fare forward, voyagers."
   echo ""
fi


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
